---
title: "Blood Pressure Notebook"
output: html_notebook
---


```{r libraries}
# library("dplyr")
library("lubridate")
# library("readr")
# library("stringr")
# library("ggplot2")
# library("tidyr")
library(tidyverse)
```

```{r rely_on_health_df}
source("R/create_bp_dataset.R")
# creates bp_omron, qardio, bp_omron1, bp_omron2, bp_omron3
```

```{r read_from_csv}
# Based on blood pressure data in Blood Pressure.numbers in the Personal folder in Dropbox.
# Exported to csv in the John Vitals folder.
bp_spreadsheet <- read_csv("Blood Pressure.csv", col_types = cols(
  date = col_date("%m/%d/%Y"),
  time = col_character(),
  adjusted_date = col_date("%m/%d/%Y"),
  adjusted_time = col_character(),
  systolic = col_double(),
  diastolic = col_double(),
  pulse = col_double()
))
usethis::ui_info("Latest blood pressure from CSV {max(bp_spreadsheet$date, na.rm = TRUE)}.")

bp_spreadsheet <- filter(bp_spreadsheet, !is.na(date))
bp_spreadsheet$char_when <- ifelse(is.na(bp_spreadsheet$adjusted_date), paste(bp_spreadsheet$date, bp_spreadsheet$time), paste(bp_spreadsheet$adjusted_date, bp_spreadsheet$adjusted_time))
bp_spreadsheet$char_when[str_detect(bp_spreadsheet$char_when, "12:")] <- str_replace(bp_spreadsheet$char_when[str_detect(bp_spreadsheet$char_when, "12:")], "12:", "00:")

bp_spreadsheet$when <- parse_datetime(bp_spreadsheet$char_when, format = "%Y-%m-%d %H:%M %p")

type_levels <- c("systolic", "diastolic", "pulse", "resting heart rate", "step count", "weight")

# Let's get things tidy before we do anything else.
# gather the spreadsheet to tidy it:
bp_manual <-  gather(bp_spreadsheet, key = type, value= value, systolic, diastolic, pulse) %>%
  mutate(source = ifelse(source == "Vitals", "vitals", source)) |> 
  select(when, type, value, source, note) %>%
  filter((source != "exclude") | is.na(source))

# bp_manual <- bp_spreadsheet |> 
#   pivot_longer(cols = c(systolic, diastolic, pulse), names_to = "type")

bp_ds <- bind_rows(bp_manual |>  select(names(bp_omron)), 
                   bp_omron)

dr_young <- ymd_hms("2015-11-23 9:00:00")

# readings that are within some time limit of each other should be treated as a single group
bp1 <- bp_ds %>%
  group_by(type, source) %>%
  arrange(when) %>%
  mutate(
    time_group =  cumsum(case_when(
      is.na(lag(when)) ~ 1,
      TRUE ~ as.numeric(difftime(when, lag(when), units = "mins") > 40)
    )),
  )
bp1$type <- factor(bp1$type, levels = type_levels)

bp_group <- filter(bp1, is.na(source) | ((source != "vitals") & (source != "exclude") & (source != "wrist-odd")))  |> 
  mutate(date = as_date(when)) |> 
  group_by(type, source, date, time_group) |> 
  summarise(value = mean(value), when = mean(when), n = n()) 
  
bp_group$type <- factor(bp_group$type, levels = type_levels)

# bp_group3 is same as bp_group except if there are multiple groups in a day it only includes the first one
bp_group3 <- bp_group %>% 
  group_by(type, source, date) %>%
  arrange(time_group) %>%
  filter(time_group == first(time_group))
bp_group3$type <- factor(bp_group3$type, levels = type_levels)

# bp_group4 will be true mean per day
bp_group4 <- bp_group %>% 
  group_by(type, date) %>%
  summarise(value = mean(value, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(source = "mean per day", time_group = 1, when = as_datetime(date),
         type = factor(type, levels = type_levels)) 
  
# chart_1stperday <- ggplot(data = bp_group3,
#                           aes(x = when, y = value)) 
# chart_1stperday <- chart_1stperday + geom_point() + facet_wrap(~ type, ncol = 1, scales = "free_y") + 
#   ggtitle("Maximum One Group Reading per Day (Earliest)")
# chart_1stperday <- chart_1stperday + geom_vline(xintercept = as.numeric(floor_date(dr_young, unit = "day")), colour = "yellow", size = 1)

# bp_group5 takes bp_group and averages grouped readings by day
# bp_group5 <- group_by(bp_group, date) %>% arrange(date, time_group) %>% summarise(systolic = mean(systolic), diastolic = mean(diastolic), pulse = mean(pulse), when = mean(when))

# 
# bp_group2 <- gather(bp_group, type, value, systolic, diastolic, pulse)
# 
# bp_group_all <- filter(bp2, is.na(source) |  (source != "exclude")) %>%
#   group_by(group) %>% summarise(systolic = mean(systolic), diastolic = mean(diastolic), pulse = mean(pulse), when = mean(when))
# bp_group2_all <- gather(bp_group_all, type, value, systolic, diastolic, pulse)

bp_ranges <- data.frame(h = c(130, 80, NA), type = c("systolic", "diastolic", "pulse"))
events_base <- tibble(when = c("11/23/2015 09:00 AM",  
                               "01/28/2016 02:00 PM", "07/07/2017 10:00 AM",
                               "01/02/2018 10:00 AM", "02/25/2019 05:30 AM",
                               "10/25/2020 01:30 PM", "05/17/2021 11:00 AM",
                               "10/13/2021 03:30 PM"), 
                      what = c("Young", "Basal", "Move", "House", "ER", "afib", "PAI", "Fall"),
                      type = "systolic")
events_base$when <- parse_datetime(events_base$when, format = "%m/%d/%Y %H:%M %p")
events_base$y = min(bp_group$value[bp_group$type == "systolic"])
events_base$yend = events_base$y + 5
events_base$type <- factor(events_base$type, levels = type_levels)
events <- events_base
events_base$type <- "diastolic"
events_base$y = min(bp_group$value[bp_group$type == "diastolic"])
events_base$yend = events_base$y + 4
events_base$type <- factor(events_base$type, levels = type_levels)
events <- bind_rows(events, events_base)
events_base$type <- "pulse"
events_base$type <- factor(events_base$type, levels = type_levels)
events_base$y = min(bp_group$value[bp_group$type == "pulse"])
events_base$yend = events_base$y + 4
events <- bind_rows(events, events_base)
events$type <- factor(events$type, levels = type_levels)
#bp_group$type <- factor(bp_group$type, levels = type_levels)
```
```{r by_time_group, eval = FALSE}
# I'm not sure what this block was intended to be
places <- bp_group |> 
  # filter(!(source %in% c("vitals", "exclude", "wrist-odd", "wrist-wrong"))) |> 
  group_by(type, date, time_group) |> 
  arrange(when) %>%
  # filter(type == "systolic") |> 
  mutate(
    place =  seq(1, n()),
    decrease = first(value) - value
  ) |> 
  filter(place <= 4)
xx |> 
  group_by(type, place) |> 
  summarise(decrease = mean(decrease, na.rm = TRUE), sd = sd(decrease), n = n())
outliers <- xx |> filter(abs(decrease) > 25)
```

At this point, data is setup. I hope. Now let's do some charts.

```{r bp_per_day}
month_year <- function(x, first_month = 1) {
  paste0(month(x, label = TRUE), "\n", ifelse(month(x) <= (first_month + 2), year(x), ""))
}

bp_ranges$type <- factor(bp_ranges$type, levels = type_levels)
chart_meanperday <- ggplot(data = bp_group4, aes(x = when |> as_date(), y = value)) 
chart_meanperday <- chart_meanperday + geom_hline(data = bp_ranges, aes(yintercept = h), colour = "yellow", size = 1)
chart_meanperday <- chart_meanperday + 
  geom_point(size = 1) + 
  facet_wrap(~ type, ncol = 1, scales = "free_y") + 
  ggtitle("Mean of Grouped Readings by Day", subtitle = "green dots indicate in-office vitals") + 
  xlab(NULL) + ylab(NULL) +
  geom_smooth(data = bp_group4, span = 0.10, method = "loess") 
chart_meanperday <- chart_meanperday + 
  geom_segment(data = events, aes(x = when |> as_date(), xend = when |> as_date(), y = y, yend = yend), colour = "red", arrow = arrow(length = unit(0.02, "npc"))) +
  geom_text(data = events, aes(when |> as_date(), y = y - 1, label = what), size = 2.5)
chart_meanperday <- chart_meanperday + 
  geom_point(data = filter(bp1, source == "vitals"), colour = "Green") + 
  facet_wrap(~ type, ncol = 1, scales = "free_y") + 
  scale_x_date(date_breaks = "4 months", date_minor_breaks = "1 months", 
               limits = c(ymd("2015-05-05"), NA),
                   labels = month_year) + # month_year is function I wrote
  theme(axis.text.x = element_text(size = 8)) + 
  theme(strip.text.x = element_text(size = 12, face = "bold"))

ggsave("pdfs/blood pressure plot1.pdf", plot = chart_meanperday, width = 10, height = 7)
```

```{r bp_per_day_recent}
days_hist <- 365
cutoff <- max(bp_group4$when, na.rm = TRUE) - days(days_hist)
chart_meanperday_recent <- ggplot(data = bp_group4 %>% filter(when >= cutoff), aes(x = when, y = value)) 
chart_meanperday_recent <- chart_meanperday_recent + geom_hline(data = bp_ranges, aes(yintercept = h), colour = "yellow", size = 1)
chart_meanperday_recent <- chart_meanperday_recent + geom_point() + facet_wrap(~ type, ncol = 1, scales = "free_y") + 
  ggtitle(glue::glue("Mean of Grouped Readings by Day (last {days_hist} days)"), subtitle = "green dots indicate in-office vitals") + 
  xlab(NULL) + ylab(NULL) +
  geom_smooth(data = bp_group4 %>% filter(when >= cutoff), span = 0.10) 
chart_meanperday_recent <- chart_meanperday_recent + geom_segment(data = events %>% filter(when >= cutoff), 
                                                    aes(x = when, xend = when, y = y, yend = yend), 
                                                    colour = "red", arrow = arrow(length = unit(0.03, "npc")))
chart_meanperday_recent <- chart_meanperday_recent + geom_point(data = filter(bp1, source == "vitals", when >= cutoff), colour = "Green") + 
  facet_wrap(~ type, ncol = 1, scales = "free_y") 
chart_meanperday_recent <- chart_meanperday_recent + scale_x_datetime(date_breaks = "2 months", date_minor_breaks = "1 months", labels = month_year)
chart_meanperday_recent <- chart_meanperday_recent + theme(axis.text.x = element_text(size = 8))
chart_meanperday_recent <- chart_meanperday_recent + theme(strip.text.x = element_text(size = 12, face = "bold"))

ggsave("pdfs/blood pressure recent.pdf", plot = chart_meanperday_recent, width = 10, height = 7)
```
```{r}
days_hist <- 365
cutoff <- max(bp_group4$when, na.rm = TRUE) - days(days_hist)
chart_meanperday_recent <- ggplot(data = bp_group4 %>% filter(when >= cutoff), aes(x = when, y = value)) 
chart_meanperday_recent <- ggplot(data = bp_group4 %>% filter(when >= cutoff), 
   aes(x = when |> as_date(), y = value)) 
chart_meanperday_recent <- chart_meanperday_recent + 
  geom_hline(data = bp_ranges, aes(yintercept = h), colour = "yellow", size = 1)
chart_meanperday_recent <- chart_meanperday_recent + 
  geom_point(size = 1) + 
  facet_wrap(~ type, ncol = 1, scales = "free_y") + 
  ggtitle("Mean of Grouped Readings by Day", subtitle = "green dots indicate in-office vitals") + 
  xlab(NULL) + ylab(NULL) +
  geom_smooth(data = bp_group4 %>% filter(when >= cutoff), 
              span = 0.10, method = "loess") 
chart_meanperday_recent <- chart_meanperday_recent + 
  geom_segment(data = events %>% filter(when >= cutoff), 
               aes(x = when |> as_date(), xend = when |> as_date(), y = y, yend = yend), colour = "red", arrow = arrow(length = unit(0.02, "npc"))) +
  geom_text(data = events %>% filter(when >= cutoff), 
            aes(when |> as_date(), y = y - 1, label = what), size = 2.5)
chart_meanperday_recent <- chart_meanperday_recent + 
  geom_point(data = filter(bp1, source == "vitals", when >= cutoff), colour = "Green") + 
  facet_wrap(~ type, ncol = 1, scales = "free_y") + 
  scale_x_date(date_breaks = "2 months", date_minor_breaks = "1 months", labels = month_year) +
  # scale_x_date(date_breaks = "4 months", date_minor_breaks = "1 months", 
  #                  labels = month_year) + # month_year is function I wrote
  theme(axis.text.x = element_text(size = 8)) + 
  theme(strip.text.x = element_text(size = 12, face = "bold"))
ggsave("pdfs/blood pressure recent.pdf", plot = chart_meanperday_recent, width = 10, height = 7)
```


```{r with_n}
bp_group3 <- bp_group3 %>% mutate(multiples = (n > 1))
chart_with_n <- ggplot(data = bp_group3, aes(x = when, y = value)) 
chart_with_n <- chart_with_n + geom_hline(data = bp_ranges, aes(yintercept = h), colour = "yellow", size = 1)
chart_with_n <- chart_with_n + geom_point(aes(colour = factor(multiples)), size = 0.5) + facet_wrap(~ type, ncol = 1, scales = "free_y") + 
  ggtitle("Mean of Grouped Readings by Day", subtitle = "green dots indicate in-office vitals") + 
  xlab(NULL) + ylab(NULL) +
  geom_smooth(data = bp_group3, span = 0.001) 
chart_with_n <- chart_with_n + geom_segment(data = events, aes(x = when, xend = when, y = y, yend = yend), colour = "red", arrow = arrow(length = unit(0.03, "npc")))
chart_with_n <- chart_with_n + geom_point(data = filter(bp1, source == "vitals"), colour = "Green",size = 0.6) + 
  facet_wrap(~ type, ncol = 1, scales = "free_y") 
chart_with_n <- chart_with_n + scale_x_datetime(date_breaks = "3 months", date_minor_breaks = "1 months", labels = month_year)
chart_with_n <- chart_with_n + theme(axis.text.x = element_text(size = 8))
chart_with_n <- chart_with_n + theme(strip.text.x = element_text(size = 12, face = "bold"))




if (exists("df_resting_hr") & exists("watch_step_count")) {
  watch_step_count <- watch_step_count %>% 
    mutate(source = "Watch", time_group = 1, when = as_datetime(date), type = "step count", type = factor(type, type_levels))
  bp_group4_with_hr <- bp_group4 %>% 
    bind_rows((df_resting_hr %>% select(type, value, date, when = start_date, source, time_group)), watch_step_count)


  chart_meanperday2 <- ggplot(data = bp_group4_with_hr, aes(x = when, y = value)) 
  chart_meanperday2 <- chart_meanperday2 + geom_hline(data = bp_ranges, aes(yintercept = h), colour = "yellow", size = 1)
  chart_meanperday2 <- chart_meanperday2 + geom_point(size = 1) + facet_wrap(~ type, ncol = 1, scales = "free_y") + 
    ggtitle("Mean of Grouped Readings by Day", subtitle = "green dots indicate in-office vitals") + 
    xlab(NULL) + ylab(NULL) +
    geom_smooth(data = bp_group4, span = 0.10) 
  chart_meanperday2 <- chart_meanperday2 + geom_segment(data = events, aes(x = when, xend = when, y = y, yend = yend), colour = "red", arrow = arrow(length = unit(0.03, "npc")))
  chart_meanperday2 <- chart_meanperday2 + geom_point(data = filter(bp1, source == "vitals"), colour = "Green") + 
    facet_wrap(~ type, ncol = 1, scales = "free_y") 
  chart_meanperday2 <- chart_meanperday2 + scale_x_datetime(date_breaks = "3 months", date_minor_breaks = "1 months", labels = month_year)
  chart_meanperday2 <- chart_meanperday2 + theme(axis.text.x = element_text(size = 8))
  chart_meanperday2 <- chart_meanperday2 + theme(strip.text.x = element_text(size = 12, face = "bold"))
  
    chart_meanperday3 <- ggplot(data = bp_group4_with_hr %>% filter(when >= min(watch_step_count$when, na.rm = TRUE)), aes(x = when, y = value)) 
  chart_meanperday3 <- chart_meanperday3 + xlim(as_datetime(ymd(min(watch_step_count$date, na.rm = TRUE))), as_datetime(ymd(max(watch_step_count$date, na.rm = TRUE)))) 
  chart_meanperday3 <- chart_meanperday3 + geom_hline(data = bp_ranges, aes(yintercept = h), colour = "yellow", size = 1)
  chart_meanperday3 <- chart_meanperday3 + geom_point() + facet_wrap(~ type, ncol = 1, scales = "free_y") + 
    ggtitle("Mean of Grouped Readings by Day", subtitle = "green dots indicate in-office vitals") + 
    xlab(NULL) + ylab(NULL) +
    geom_smooth(data = bp_group4_with_hr %>% filter(when >= min(watch_step_count$when, na.rm = TRUE)), span = 0.10) 
  chart_meanperday3 <- chart_meanperday3 + geom_segment(data = events %>% filter(when >= min(watch_step_count$when, na.rm = TRUE)), aes(x = when, xend = when, y = y, yend = yend), colour = "red", arrow = arrow(length = unit(0.03, "npc")))
  chart_meanperday3 <- chart_meanperday3 + geom_point(data = filter(bp1, source == "vitals", (when >= min(watch_step_count$when, na.rm = TRUE))), colour = "Green") + 
    facet_wrap(~ type, ncol = 1, scales = "free_y") 
  chart_meanperday3 <- chart_meanperday3 + theme(axis.text.x = element_text(size = 8))
  chart_meanperday3 <- chart_meanperday3 + theme(strip.text.x = element_text(size = 12, face = "bold")) +
    scale_x_datetime(date_breaks = "3 months", date_minor_breaks = "1 months", labels = month_year)
  ggsave("blood pressure plot3.pdf", plot = chart_meanperday3, width = 10, height = 7)
}

```

```{r bp_pulse}
bp_spread <- bp_group4 %>% spread(key = type, value = value)
pulse_systolic <- ggplot(data = bp_spread, aes(x = pulse, y = systolic)) +
  geom_point() + 
  ggtitle("Pulse and Systolic BP") +
  xlab("Pulse") + ylab("Systolic")  +
  geom_smooth()
  # geom_smooth(method = "lm")
pulse_diastolic <- ggplot(data = bp_spread, aes(x = pulse, y = diastolic)) +
  geom_point() + 
  ggtitle("Pulse and Diastolic BP") +
  xlab("Pulse") + ylab("Diastolic") +
    geom_smooth()

diastolic_systolic <- ggplot(data = bp_spread, aes(x = diastolic, y = systolic)) +
  geom_point() + 
  ggtitle("Diastollic and Systolic BP") +
  xlab("Diastolic") + ylab("Systolic") +
  geom_smooth(method = "lm")
```


```{r time_of_day}
bp_group3$hour <- hour(bp_group3$when) + minute(bp_group3$when)/60
chart_hour <- ggplot(data = bp_group3, aes(x = hour, y = value)) 
chart_hour <- chart_hour + geom_hline(data = bp_ranges, aes(yintercept = h), colour = "yellow", size = 1)
chart_hour <- chart_hour + geom_point() + facet_wrap(~ type, ncol = 1, scales = "free_y") + 
  ggtitle("Mean of Grouped Readings by Day", subtitle = "green dots indicate in-office vitals") + 
  xlab(NULL) + ylab(NULL)+
  geom_smooth(data = bp_group3, span = 0.10) 
chart_hour <- chart_hour + geom_segment(data = events, aes(x = hour, xend = hour, y = y, yend = yend), colour = "red", arrow = arrow(length = unit(0.03, "npc")))
chart_hour <- chart_hour + geom_point(data = filter(bp1, source == "vitals"), colour = "Green") + 
  facet_wrap(~ type, ncol = 1, scales = "free_y") 


```
