---
title: "heart_rate_analysis"
author: "John Goldin"
date: "2/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup_libs, echo = FALSE}
library(tidyverse)
library(jsonlite)
library(lubridate)
library(ggplot2)
library(scales)
library(XML)
```

```{r load_data, cache = TRUE, echo = FALSE}
# load("full_data_from_Apple_Health.RData")
# Using example from github: https://gist.github.com/ryanpraski/ba9baee2583cfb1af88ca4ec62311a3d
# ryanpraski/apple_health_load_analysis_R.r
# http://www.ryanpraski.com/apple-health-data-how-to-export-analyze-visualize-guide/

# see also:  https://github.com/deepankardatta/AppleHealthAnalysis

#load apple health export.xml file
xml <- xmlParse("apple_health_export/export.xml")

#json_example <- read_json("apple_health_export/export.xml")
#transform xml file to data frame - select the Record rows from the xml file
df <- XML:::xmlAttrsToDataFrame(xml["//Record"])

#make value variable numeric
df$value <- as.numeric(as.character(df$value))


#make endDate in a date time variable POSIXct using lubridate with eastern time zone
df$endDate <-ymd_hms(df$endDate,tz="America/New_York")
df$startDate <-ymd_hms(df$startDate,tz="America/New_York")

##add in year month date dayofweek hour columns
df$month<-format(df$endDate,"%m")
df$year<-format(df$endDate,"%Y")
df$date<-format(df$endDate,"%Y-%m-%d")
df$dayofweek <-wday(df$endDate, label=TRUE, abbr=FALSE)
df$hour <-format(df$endDate,"%H")

steps <- df %>%
  filter(type == 'HKQuantityTypeIdentifierStepCount') %>%
  group_by(date) %>% 
  mutate(steps = as.numeric(as.character(value))) %>%
  summarise(steps = sum(steps))
distance <- df %>%
  filter(type == 'HKQuantityTypeIdentifierDistanceWalkingRunning') %>%
  group_by(date) %>% 
  mutate(distance = as.numeric(as.character(value))) %>%
  summarise(distance = sum(distance))
#filter(steps, month(date) == 5, year(date) == 2016) %>% print(n=1000)

```
```{r create_plot, echo = FALSE}
plot_day <- function(adf, adate, events = FALSE, hour_min = NULL, hour_max = NULL) {
  print(hour_max)
  adf <- adf %>% filter(type %in% c("HKQuantityTypeIdentifierHeartRate", "HeartRate"), date %in% adate) %>%
    arrange(start_date)
  if (!is.null(hour_max)) adf <- adf %>% filter(hour(start_date) <= hour_max)
  if (!is.null(hour_min)) adf <- adf %>% filter(hour(start_date) >= hour_min)
  p <- ggplot(data = adf, aes(x = start_date, y = value))
  if (events) {
    base <- adf$start_date[10]
    left_house <- base
    hour(left_house) <- 5
    minute(left_house) <- 55
    arrived <- base
    hour(arrived) <- 6
    minute(arrived) <- 3
    p <- p + geom_vline(xintercept = left_house, colour = "yellow") +
      geom_vline(xintercept = arrived, colour = "yellow")
  }
  p <- p + geom_point(size = 0.3) +
    xlab("Time (Hour)") + ylab("Pulse (Apple Watch)") +
    scale_x_datetime(date_labels = "%H", breaks = date_breaks("1 hour"),
                     minor_breaks = date_breaks("10 min")) + 
    facet_wrap(~ date, ncol = 1, scales = "free_x")
}
```


https://www.cnn.com/2019/03/16/health/apple-watch-heart-rate-arrhythmia-afib-study/index.html
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6111985/

```{r}
p <- plot_day(health_df, c(ymd("2020-10-25")), events = TRUE, hour_min = 8, hour_max = 15)

days_events <- tribble(
  ~x, ~lab, 
  as_datetime("2020-10-25 12:30:00"), "ECG",
  as_datetime("2020-10-25 13:47:00"), "ECG"
)
ynhh <- tribble(
  ~x, ~lab,
  as_datetime("2020-10-25 14:04:00"),
  "arrive at ER"
)
p <- p  + geom_segment(data = days_events, aes(x = x, xend = x, y = 154, yend = 159.3), colour = "orange", arrow = arrow(angle = 20, ends = "first", length = unit(0.03, "npc"))) + 
  geom_text(data = days_events, aes(x = x, y = 155, label = lab), hjust = 0.5, color = "orange", nudge_y = 5, size = 2) +
    geom_segment(data = ynhh, aes(x = x, xend = x, y = 154, yend = 159.3), colour = "blue", arrow = arrow(angle = 20, ends = "first", length = unit(0.03, "npc"))) +
  geom_text(data = ynhh, aes(x = x, y = 155, label = lab), hjust = 0, color = "blue", nudge_y = 5, size = 3) +
  annotate("label", y = 130, x = as_datetime("2020-10-25 11:11:00"),
           xmin =  as_datetime("2020-10-25 10:41:00"), xmax = as_datetime("2020-10-25 11:50:00"),
           label = "walk in Westwoods", size = 3)
ggsave("pdfs/ER visit John Goldin 10-25-2020.pdf", width = 6.5, height = 4.5 )

ptoday <- plot_day(health_df, c(today()), events = TRUE, hour_min = 8, hour_max = 15)


# health_df %>% filter(as_date(start_date) ==  ymd("2019-02-16")) %>% arrange(start_date) %>% View()
```



```{r}
plot_day(health_df, ymd("2019-02-15"), events = TRUE, hour_min = 1, hour_max = 2) %>% print()

# health_df %>% filter(as_date(start_date) ==  ymd("2019-02-16")) %>% arrange(start_date) %>% View()
```


```{r}
plot_day(health_df, ymd("2020-10-25"),  hour_min = 8, hour_max = 15) %>% print()
plot_day(health_df, ymd("2020-11-01"),  hour_min = 6, hour_max = 12) %>% print()


# health_df %>% filter(as_date(start_date) ==  ymd("2019-02-16")) %>% arrange(start_date) %>% View()
```



```{r anomalous_readings, echo = FALSE, eval = FALSE}
df <- df  %>% filter(type == "HKQuantityTypeIdentifierHeartRate", start_date >= ymd("2017-10-01")) 
above145 <- df %>% filter(type == "HKQuantityTypeIdentifierHeartRate", value >= 145 ) %>%
  arrange(start_date) %>%
  select(start_date, value, dayofweek, hour, date, type, year)
table(above145$date)
plot_day(df, "2019-02-02") %>% print()

above145_night <- df %>% filter(type == "HKQuantityTypeIdentifierHeartRate", value >= 145,
                                (as.numeric(hour) <= 6) | (as.numeric(hour) >= 23)) %>%
                                # (hour <= 6) ) %>%
  arrange(start_date) %>%
  select(start_date, value, dayofweek, hour, date, type, year)
# This gives us four dates, one of which is 2/15/2019.
```


```{r summary}
p15th <- plot_day(df, "2019-02-15", hour_min = 0, hour_max = 24)

weird_dates <- c("2018-08-24", "2018-08-26", "2018-03-27", "2018-06-13")
weird_plot <- plot_day(df, weird_dates, hour_min = 0, hour_max = 24)
strenuous <- plot_day(df, c("2018-03-24", "2018-06-12", "2018-04-13", "2018-04-08"), hour_min = 0, hour_max = 24)
```


```{r}
vhr <- df %>% filter(type == "HKQuantityTypeIdentifierHeartRateVariabilitySDNN")
```

