---
title: "R Notebook"
output: html_notebook
---

Let's figure out watch version breaks

```{r first_try, eval = FALSE}
versions <- unique(health_df %>% filter(str_detect(sourceName, "Watch"), !is.na(sourceVersion)) %>% 
                     select(sourceVersion)) %>% 
                     separate(sourceVersion, into = c("major", "minor", "subminor"), remove = FALSE) %>% 
  mutate(subminor = ifelse(is.na(subminor), "0", subminor)) %>% 
  arrange(sourceVersion)

boundaries <- health_df %>% 
  filter(str_detect(sourceName, "Watch"), !is.na(sourceVersion)) %>% 
  left_join(versions, by = "sourceVersion") %>% 
  arrange(sourceVersion, local_start, creationDate) %>% 
  group_by(sourceVersion, major, minor, subminor) %>% 
  summarise(first_date = first(local_start), last_date = last(local_start))

boundaries <- boundaries %>% 
  ungroup() %>% 
  arrange(first_date) %>% 
  mutate(test = lag(major),
         test2 = lead(major),
    level = case_when(
    major != lag(major) ~ 3,
    minor != lag(minor) ~ 2,
    subminor != lag(subminor) ~ 1,
    TRUE ~ NA_real_
  ))

```
```{r bp_hr, eval = FALSE}
bp_hr <- bp_omron %>% 
  mutate(local_date = as_date(when)) %>% 
  group_by(local_date) %>% 
  filter(type == "pulse") %>% 
  summarise(value = min(value), na.rm = TRUE, .groups = "drop")
```



```{r hr_boundaries}
hr <- health_df %>% 
  filter(type == "RestingHeartRate")

hr_versions <- unique(hr %>% filter(str_detect(sourceName, "Watch"), !is.na(sourceVersion)) %>% 
                     select(sourceVersion)) %>% 
                     separate(sourceVersion, into = c("major", "minor", "subminor"), remove = FALSE) %>% 
  mutate(subminor = ifelse(is.na(subminor), "0", subminor)) %>% 
  arrange(sourceVersion)

hr_boundaries <- hr %>% 
  left_join(versions, by = "sourceVersion") %>% 
  arrange(sourceVersion, local_start, creationDate) %>% 
  group_by(sourceVersion, major, minor, subminor) %>% 
  summarise(first_date = first(local_start), last_date = last(local_start))

hr_boundaries <- hr_boundaries %>% 
  ungroup() %>% 
  arrange(first_date) %>% 
  mutate(test = lag(major),
         test2 = lead(major),
    level = case_when(
    major != lag(major) ~ 3,
    minor != lag(minor) ~ 2,
    subminor != lag(subminor) ~ 1,
    TRUE ~ NA_real_
  ))
p_noversion1 <- ggplot(data = hr, aes(x = local_date, y = value)) +
  ylab("resting heart rate") + xlab(NULL) +
  ggtitle("Resting Heart Rate by Day") +
  geom_point(size = 0.5) 
p_noversion2 <- p_noversion1 +
  geom_smooth()
p_version1 <- p_noversion2 +
  geom_vline(data = hr_boundaries %>% filter(level == 3), 
             aes(xintercept = as_date(first_date)), size = 1, colour = "seagreen3") +
  geom_vline(data = hr_boundaries %>% filter(level == 2), 
             aes(xintercept = as_date(first_date)), size = 0.3, colour = "seagreen2") 
big_change <- boundaries$first_date[boundaries$sourceVersion == "7.0"] %>% as_date()
p_version2 <- p_noversion1 +
  geom_smooth(data = hr %>% filter(local_date < big_change)) +
  geom_smooth(data = hr %>% filter(local_date >= big_change)) 

p + geom_point(data = bp_hr, size = 0.5, colour = "yellow") +
  geom_smooth(data = bp_hr, span = 0.1, method = "loess")
```

```{r vo2max}
vo2max <- health_df %>% 
  filter(type == "VO2Max")
vo_versions <- unique(vo2max %>% filter(type == "VO2Max", !is.na(sourceVersion)) %>% 
                     select(sourceVersion)) %>% 
                     separate(sourceVersion, into = c("major", "minor", "subminor"), remove = FALSE) %>% 
  mutate(subminor = ifelse(is.na(subminor), "0", subminor), major = as.numeric(major),
         minor = as.numeric(minor), subminor = as.numeric(subminor)) %>% 
  arrange(major, minor, subminor)
vo2max2 <- vo2max %>% 
  left_join(vo_versions, by = "sourceVersion") %>% 
  arrange(sourceVersion, local_start, creationDate)
vo_boundaries <- vo2max2 %>% 
  group_by(major, minor, subminor) %>% 
  summarise(first_date = first(local_start), last_date = last(local_start))

vo_boundaries <- vo_boundaries %>% 
  ungroup() %>% 
  arrange(first_date) %>% 
  mutate(test = lag(major),
         test2 = lead(major),
    level = case_when(
    (major != lag(major)) | ((major > 0) & is.na(lag(major))) ~ 3,
    is.na(lag(major)) ~ 0,
    minor != lag(minor) ~ 2,
    subminor != lag(subminor) ~ 1,
    TRUE ~ NA_real_
  ))
p_vo2max1 <- ggplot(data = vo2max, aes(x = local_date, y = value)) +
  ylab("VO2 Max") + xlab(NULL) +
  ggtitle("Estimated VO2 Max") +
  geom_point(size = 0.5) 
p_vo2max2 <- p_vo2max1 # no smooth
p_vo2max3 <- p_vo2max2 +
  geom_vline(data = vo_boundaries %>% filter(level == 3), 
             aes(xintercept = as_date(first_date)), size = 1, colour = "goldenrod1") +
  geom_vline(data = vo_boundaries %>% filter(level == 2), 
             aes(xintercept = as_date(first_date)), size = 0.3, colour = "goldenrod3") +
  geom_vline(data = hr_boundaries %>% filter(level == 3), 
             aes(xintercept = as_date(first_date)), size = 1, colour = "seagreen3") +
  geom_vline(data = hr_boundaries %>% filter(level == 2), 
             aes(xintercept = as_date(first_date)), size = 0.3, colour = "seagreen2") 
big_change <- boundaries$first_date[boundaries$sourceVersion == "7.0"] %>% as_date()


```


```{r, eval = FALSE}
# get heart rate data
heart_rate <- health_df %>% 
  filter(type == "HeartRate", str_detect(sourceName, "Watch"))
hr_by_day <- heart_rate %>% 
  group_by(local_date) %>% 
  #I don't believe values below 44 (arbitrary) are valid. Most are in 2017 or 2018.
  filter(value >= 44) %>% 
  summarise(lowest = min(value, na.rm = TRUE), 
            very_low = quantile(value, probs = 0.04, na.rm = TRUE), .groups = "drop")
# when did we get more than one resting heart rate in a day (because of travel across time zones)
duplicate_dates <- hr %>% count(local_date) %>% filter(n > 1) %>% pluck("local_date")    
compare_hr <- hr %>% filter(!(local_date %in% duplicate_dates), major_version != "7") %>% 
  select(local_date, resting = value) %>% 
  left_join(hr_by_day, by = "local_date")

ggplot(data = compare_hr %>% filter(very_low < 60), aes(x = lowest, y = resting)) +
  # geom_point(size = 0.2, colour = "red", position = "jitter") + geom_smooth(method = "lm", colour = "red") +
  geom_point(aes(x = very_low, y = resting), size = 0.2, colour = "blue") +
  geom_smooth(aes(x = very_low, y = resting), method = "lm", colour = "blue") +
  xlab("heart rate 0.04 percentle") + ylab("reported resting heart rate") +
  geom_abline(slope = 1, intercept = 0, colour = "block")

```

```{r, eval = FALSE}
# create my own versions of resting heart rate for wake and sleep periods
low_hr <- heart_rate %>% 
  mutate(
    sleep_hr = if_else(Period == "Sleep", value, NA_real_),
    wake_hr = if_else(Period == "Day", value, NA_real_)
  ) %>% 
  filter(Period != "Workout") %>% 
  group_by(local_date, Period) %>% 
  summarise(low_hr =  quantile(value, probs = 0.04, na.rm = TRUE), .groups = "drop")  %>% 
  pivot_wider(names_from = Period, values_from = low_hr)  %>% 
  rename(resting_day = Day, resting_sleep = Sleep)

revised_resting_hr <- hr %>% filter(!(local_date %in% duplicate_dates)) %>% 
  mutate(hr_versions = if_else(major_version != "7", "earlier", "version 7")) %>% 
  select(type,
         apple_resting_hr = value, hr_versions, 
         sourceName, sourceVersion, local_date, Version, major_version) %>% 
  left_join(low_hr, by = "local_date") 

ggplot(data = revised_resting_hr, aes(x = apple_resting_hr, y = low_hr, shape = hr_versions)) +
  geom_point() +
  facet_wrap(~ Period)

```

```{r, eval = FALSE}
library(tsibble)
library(feasts)
xx <- compare_hr %>% 
  filter(major_version != "7") %>% 
  select(apple_resting_hr, local_date) %>% 
  as_tsibble(index = local_date) %>% 
  fill_gaps()
xx %>%
  model(
    classical_decomposition(apple_resting_hr, type = "additive")
  ) %>%
  components() %>%
  autoplot()
```

